@startuml
start
:Получение запросов \nот внешних сервисов;
if (Валидация\nструктуры данных?) then (да)
  :Обработка данных каждого источника;
  fork
    :Извлечение данных\n"модель.json";
  fork again
    :Извлечение данных\n"объединенное_кредитное_бюро.json";
  fork again
    :Извлечение данных\n"ресурс_комитета_по_образованию.json";
  fork again
    :Извлечение данных\n"федресурс.json";
  end fork
  :Сопоставление и объединение данных;
  :Нормализация данных;
  :Формирование анкеты\n"анкета_на_получение_кредита.json";
  :Сохранение JSON-файла;
else (нет)
  :Возврат ошибки;
endif
stop
@enduml



