@startuml
skinparam defaultTextAlignment center
:Сформирована анкета\n//"анкета_на_получение_кредита.json"//;
start
:**GigaChat_func()**\nпарсинг анкеты и создание\n**Payload** запросов для внешних систем;
:**Rq/Rs** к\nвнешним сервисам;
if (\nВалидация\n**Ok?**\n) then (да)
  :Обработка ответа каждого источника;
  fork
    :**GigaChat_func():**\n извлечение и агрегация данных из\n//"объединенное_кредитное_бюро.json"//;
  fork again
    :**GigaChat_func():**\n извлечение и агрегация данных из\n//"ресурс_комитета_по_образованию.json"//;
  fork again
    :**GigaChat_func():**\n извлечение данных из\n//"федресурс.json"//;
  end fork
  :Сопоставление и объединение данных;
  :Нормализация данных;
  :Cоединение данных\n в Запрос //"модель.json"//;
else (нет)
  :Возврат\nкода ошибки;
  stop
endif

stop
@enduml