@startuml
skinparam defaultTextAlignment center
:**Подготовлены исходные данные:**
1. Данные внешних источников
2. Схема данных внешних источников
3. Схема данных запроса к AI-модели;
start
:**Обработка данных внешних источников**\nформирование нового набора данных:\n//{schema.description: json.value}//;
:**Формирование promt**\n //{schema.description: json.value}// + \n //{schema.ai_model}//;
:**Запрос к GigaChat**\nКак кредитный менеджер, с учетом входных JSON-данных\n//{schema.description: json.value}//\nрассчитай значения для атрибутов указанных в JSON-схеме\n//{schema.ai_model}//\nи сформировать JSON для оценки заемщика\nВерни данные в формате JSON без комментариев и лишнего текста;
if (\nВалидация\n**Ok?**\n) then (да)
  :Возврат тела запроса\n для //"модель.json"//;
else (нет)
  :Возврат\nкода ошибки;
  stop
endif

stop
@enduml