@startuml
start
:Получение запросов от внешних сервисов;
if (Валидация структуры данных?) then (да)
  :Обработка данных каждого источника;
  fork
    :Извлечение данных из "модель.json";
  fork again
    :Извлечение данных из "объединенное_кредитное_бюро.json";
  fork again
    :Извлечение данных из "ресурс_комитета_по_образованию.json";
  fork again
    :Извлечение данных из "федресурс.json";
  end fork
  :Сопоставление и объединение данных;
  :Нормализация данных;
  :Формирование анкеты "анкета_на_получение_кредита.json";
  :Сохранение JSON-файла;
else (нет)
  :Возврат ошибки;
endif
stop
@enduml



